version: "3.6"

services:
    api:
        environment:
            - APP_API_FILE=openapi_v1_0_0.yaml
            - APP_DEBUG_MODE=True
            - APP_HOST=0.0.0.0
            - APP_PORT=8000
            - APP_SPEC_DIR=./resources
            - APP_TEST_MODE=False
            - APP_VERSION=1.0.0
            - PYTHONUNBUFFERED=1
        container_name: gazola_api
        image: gazola_api:dev-elk
        build:
            context: ./api/resources
            args:
            - PIP_OPTIONS=--dev --skip-lock --system
            - IMAGE_DESCRIPTION=Gazola Machine Learning REST API, development-elk image
        networks:
            - gazola_api
            - gazola_elk
        ports:
            - 8000:8000
        volumes:
            - ./api:/api
        healthcheck:
            test: ["CMD", "/api/resources/health_checker.py"]
            interval: 10s
            retries: 3
            start_period: 30s

    kibana:
        container_name: gazola_kibana
        image: kibana:7.8.0
        networks:
            - gazola_elk
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch

    elasticsearch:
        environment:
            - discovery.type=single-node
        container_name: gazola_elasticsearch
        image: elasticsearch:7.8.0
        networks:
            - gazola_elk
        ports:
            - 9200:9200
            - 9300:3200

networks:
    gazola_api:
        name: gazola_api_public
    gazola_elk:
        name: gazola_elk_private
