version: "3.6"

services:
    api:
        container_name: gazola_ml_python_rest
        image: gazola_ml_python_rest:0.0.1
        build: ./api/resources
        networks:
            - gazola_ml_python_rest_public
        ports:
            - 8000:8000
        volumes:
            - ./api:/api
        healthcheck:
            test: ["CMD", "/api/resources/health_checker.py"]
            interval: 10s
            retries: 3
            start_period: 30s

networks:
    gazola_ml_python_rest_public:
        name: gazola_ml_python_rest_public_network
