openapi: 3.0.2

servers:
-   url: /v1

info:
    title: Gazola Machine Learning REST API
    description: Model trained to predict apartment's prices in São Paulo city
    license: {
        "name": "MIT License",
        "url": "https://github.com/furansa/gazola-ml-python-rest/blob/master/LICENSE"
    }
    version: 1.0.0

paths:
    /status:
        get:
            summary: Service's status
            description: Return application status
            tags:
                - Monitoring
            operationId: controllers.status.read_all
            responses:
                200:
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    status:
                                        type: string
                                        example: healthy
                                    version:
                                        type: string
                                        example: 1.0.0
    /predict:
        post:
            summary: Predict price based on given features
            description: Return the apartment's price predicted by the model
            tags:
                - Prediction
            operationId: controllers.prediction.predict
            requestBody:
                description: Set of data to feed the model
                required: true
                content:
                    application/json:
                        schema:
                            properties:
                                age:
                                    type: integer
                                    format: int64
                                    example: 25
                                size:
                                    type: number
                                    format: float
                                    example: 100.00
                            required:
                                - age
                                - size
            responses:
                200:
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                properties:
                                    price:
                                        type: number
                                        format: float
                                        example: 1000.00
